### PR TITLE
#158626106 Migrate to Zanata Translating Software

### PR DESCRIPTION
**Pull request by tonykimathi**
#### What does this PR do?
This PR transitions wger from proprietary software Transifex to open source software Zanata
#### Description of Task to be completed?
Wger is a fully open source software. Depending on closed source software is, to a certain extent, unethical and should be avoided if possible.

The are several FOSS alternatives to [Transifex](http://alternativeto.net/software/transifex/?license=opensource) and of these, Pootle seems like the best one.
#### How should this be manually tested?

- Follow the setup instructions in README.rst

- Run the app with `python manage.py runserver`

- Go to [https://translate.zanata.org/](https://translate.zanata.org/)

- Create an account and follow the setup instructions listed

- To view and edit translation documents navigate to [https://translate.zanata.org/iteration/view/wg-silicon/v1?dswid=3298](https://translate.zanata.org/iteration/view/wg-silicon/v1?dswid=3298)

#### Any background context you want to provide?
Currently, Pootle supports python up to version 2.7 which is a hinderance therefore, I opted for Zanata software in its place which supports python 3+
#### What are the relevant pivotal tracker stories?
[#158626106](https://www.pivotaltracker.com/story/show/158626106)
#### Screenshots (if appropriate)
image

### CODE REVIEW

**Comment by daktari01** [comment]
Good work on the feature @tonykimathi

**Review by muhozi — APPROVED** [review]
Good work @tonykimathi

**Review by sam-karis — APPROVED** [review]
Good work @tonykimathi this a good practices for fully open source software like wger.

**Review by kzyangiro — APPROVED** [review]
Well done @tonykimathi .

**Comment by parseen254** [comment]
LGTM

**Pull request merged**
