### PR TITLE
[Chore #158626103]relate workout log and session

### PR DESCRIPTION
**Pull request by kzyangiro**
#### What does this PR do?
Creates a relationship between workout log and workout session using a workoutsession_id foreign key on workoutlog table from workoutsession table

#### Description of Task to be completed?
Right now the workout logs and the workout session are only linked through the date (for sessions this value is unique and enforced by the DB). This presents in some places a problem, since it's not possible to just follow a foreign key relationship with the ORM like in other places. 
To fix this either:

a) see if it's possible to define the date as the foreign key in django
or
b) check if adding a real foreign key from the logs to the session makes sense

#### How should this be manually tested?
The update only affects the database. Ensure to run migrations to enable the changes take effect on the database. 
``` ./manage.py makemigrations ```

Run the tests using the command:
``` ./manage.py test```
or
#### What are the relevant pivotal tracker stories?
[#158626103](https://www.pivotaltracker.com/story/show/158626103)

### CODE REVIEW

**Review by sam-karis — APPROVED** [review]
Good work @kzyGit the approach LGTM

**Comment by tonykimathi** [comment]
Good job @kzyGit, looks like good work. However if you could add screenshots of any kind, It would be easier for anyone to understand the scope of the task you handled. Great work though 👍

**Comment by kzyangiro** [comment]
Thank you @tonykimathi , however, my task is a chore, it only modifies/improves a relation between tables in the database but does not physically affect the interface. That is why I did not include the screenshots.

**Review by muhozi — APPROVED** [review]
@kzyGit Good work.

**Pull request merged**
