### PR TITLE
#158626104 Allow comparison of members

### PR DESCRIPTION
**Pull request by sam-karis**
#### What does this PR do?
Adds bar and line chart to the gym administration page to enable comparison of weights for the active users.

#### Description of the task to be completed
When two users are training together it would be useful to see a comparison of some sorts.

How should this be manually tested

Log in as a gym administrator then navigate to the gym page
Add users and weight entries for each user.
By default the members weight comparison is by a bar chart and the gym administrator has the option of switching from bar to line chart.

#### Screenshots
image
image

### CODE REVIEW

**Comment by kzyGit** [comment]
Good work @sam-karis. The canceling effect that is great and very convenient.

**Review by muhozi — APPROVED** [review]
Good work @sam-karis

**Review by kzyangiro — APPROVED** [review]
Good work @sam-karis. The canceling effect is very convenient.

**Comment by tonykimathi** [comment]
The charts are very presentable @sam-karis. Nice implementation. 👍

**Pull request merged**
