### PR TITLE
#158626107 Add other muscles

### PR DESCRIPTION
**Pull request by muhozi**
#### What does this PR do?
- Add additional muscles
- Add pictures for those muscles
#### Description of Task to be completed?
The additional muscles were added to muscles fixtures. For now, you can you can view more muscles on the muscles overview page. And when you're going to add an exercise you can choose them.
#### How should this be manually tested?
After setting up the application. To load the fixtures just run: `invoke load-fixtures`.
#### What are the relevant pivotal tracker stories?
[#158626107](https://www.pivotaltracker.com/story/show/158626107)
#### Screenshots (if appropriate)
screen shot 2018-07-24 at 17 55 08

**Lateral deltoid muscle**

screen shot 2018-07-24 at 17 55 24

**Posterious Deltoid muscle**

screen shot 2018-07-24 at 17 54 36

**Forearms musle**

### CODE REVIEW

**Comment by tonykimathi** [comment]
Good job @muhozi. The images correctly represent the actual muscles and I'm sure users would appreciate the new muscles. 👍

**Review by sam-karis — APPROVED** [review]
Good work @muhozi, this improves user experience

**Review by kzyangiro — APPROVED** [review]
Well implemented @muhozi. A plus on improving  user experience

**Comment by daktari01** [comment]
Nice job @muhozi

**Comment by parseen254** [comment]
@muhozi muscle-19.svg does not exist making forearms invisible. Check out what's the problem.

**Comment by muhozi** [comment]
Hey @parseendavid , I renamed the corresponding muscle image. That was the problem.

**Pull request merged**
